name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Enhance GitHub Environment Variables
      run: echo "GITHUB_REF_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Install CodeClimate Reporter    
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build    

    - name: Build with Maven
      run: mvn verify -B -V

    - if: github.ref == 'refs/heads/main'
      name: Upload CodeClimate Report
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GIT_COMMIT_SHA: ${{ env.GITHUB_SHA }}
        GIT_BRANCH: ${{ env.GITHUB_REF_NAME }}
        JACOCO_SOURCE_PATH: src/main/java
      run: |
        ./cc-test-reporter format-coverage -t jacoco ./target/site/jacoco/jacoco.xml
        ./cc-test-reporter upload-coverage
